version: "3.8"

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://root:senha@db:3306/classroom_db
      - SEMESTER_API_URL=http://semester-api:5000
      - ACTIVITIES_API_URL=http://activities-api:5000
    depends_on:
      - db
      - semester-api
      - activities-api

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=senha
      - MYSQL_DATABASE=classroom_db
    ports:
      - "3306:3306"

  semester-api:
    image: matheusabreutech/api_semester_project:latest # Substitua pela imagem real
    ports:
      - "5001:5000"

  activities-api:
    image: matheusabreutech/activities_api:latest # Substitua pela imagem real
    ports:
      - "5002:5000"
