version: "3.8"

services:
  # Serviço da API Flask
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://root:senha@db:3306/classroom_db
    depends_on:
      - db
    volumes:
      - .:/app

  # Serviço do MySQL
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=senha
      - MYSQL_DATABASE=classroom_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
